name: mnist_pytorch_const
data:
  url: https://s3-us-west-2.amazonaws.com/determined-ai-test-data/pytorch_mnist.tar.gz
hyperparameters:
  learning_rate: 1.0
  global_batch_size: 64
  n_filters1: 32
  n_filters2: 64
  dropout1: 0.25
  dropout2: 0.5
searcher:
  name: single
  metric: validation_loss
  max_length:
      batches: 937 #60,000 training images with batch size 64
  smaller_is_better: true
entrypoint: model_def:MNistTrial
environment:
  environment_variables:
    - DET_MASTER=172.29.57.233
    - HTTP_PROXY=http://172.29.6.250:8080
    - HTTPS_PROXY=http://172.29.6.250:8080
    - FTP_PROXY=http://172.29.6.250:8080
    - NO_PROXY=10.104.41.208,10.110.88.18,172.29.57.233,172.29.57.112,glhc-cp-training-0.glhc-hpe.local
    - http_proxy=http://172.29.6.250:8080
    - https_proxy=http://172.29.6.250:8080
    - ftp_proxy=http://172.29.6.250:8080
    - no_proxy=10.104.41.208,10.110.88.18,172.29.57.233,172.29.57.112,glhc-cp-training-0.glhc-hpe.local
